my_string = input("Ваша страна рождения: ")
print("Вы родились в " + my_string)
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print("Ваша страна рождения: ".replace(' ',""))
print (my_string[0])
print (my_string[-1])